CREATE SCHEMA IF NOT EXISTS "public";
CREATE TYPE "Role" AS ENUM ('ADMIN', 'OPERATOR', 'VIEWER');
CREATE TYPE "DeviceStatus" AS ENUM ('ONLINE', 'OFFLINE', 'DEGRADED');
CREATE TABLE "user" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "email" TEXT NOT NULL, "emailVerified" BOOLEAN NOT NULL DEFAULT false, "image" TEXT, "role" "Role" NOT NULL DEFAULT 'VIEWER', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "user_pkey" PRIMARY KEY ("id"));
CREATE TABLE "session" ("id" TEXT NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "token" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "ipAddress" TEXT, "userAgent" TEXT, "userId" TEXT NOT NULL, CONSTRAINT "session_pkey" PRIMARY KEY ("id"));
CREATE TABLE "account" ("id" TEXT NOT NULL, "accountId" TEXT NOT NULL, "providerId" TEXT NOT NULL, "userId" TEXT NOT NULL, "accessToken" TEXT, "refreshToken" TEXT, "idToken" TEXT, "accessTokenExpiresAt" TIMESTAMP(3), "refreshTokenExpiresAt" TIMESTAMP(3), "scope" TEXT, "password" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "account_pkey" PRIMARY KEY ("id"));
CREATE TABLE "verification" ("id" TEXT NOT NULL, "identifier" TEXT NOT NULL, "value" TEXT NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "verification_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Device" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "status" "DeviceStatus" NOT NULL DEFAULT 'OFFLINE', "lastSeenAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Device_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DeviceCredential" ("id" TEXT NOT NULL, "deviceId" TEXT NOT NULL, "keyId" TEXT NOT NULL, "secretHash" TEXT NOT NULL, "revokedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "DeviceCredential_pkey" PRIMARY KEY ("id"));
CREATE TABLE "RecognitionSession" ("id" TEXT NOT NULL, "deviceId" TEXT NOT NULL, "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "endedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "RecognitionSession_pkey" PRIMARY KEY ("id"));
CREATE TABLE "RecognitionEvent" ("id" TEXT NOT NULL, "eventId" TEXT NOT NULL, "sessionId" TEXT, "deviceId" TEXT NOT NULL, "label" TEXT NOT NULL, "text" TEXT NOT NULL, "confidence" DOUBLE PRECISION NOT NULL, "occurredAt" TIMESTAMP(3) NOT NULL, "receivedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "RecognitionEvent_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "user_email_key" ON "user"("email");
CREATE UNIQUE INDEX "session_token_key" ON "session"("token");
CREATE INDEX "session_userId_idx" ON "session"("userId");
CREATE INDEX "account_userId_idx" ON "account"("userId");
CREATE INDEX "verification_identifier_idx" ON "verification"("identifier");
CREATE UNIQUE INDEX "DeviceCredential_keyId_key" ON "DeviceCredential"("keyId");
CREATE INDEX "DeviceCredential_deviceId_idx" ON "DeviceCredential"("deviceId");
CREATE INDEX "RecognitionSession_deviceId_idx" ON "RecognitionSession"("deviceId");
CREATE UNIQUE INDEX "RecognitionEvent_eventId_key" ON "RecognitionEvent"("eventId");
CREATE INDEX "RecognitionEvent_deviceId_idx" ON "RecognitionEvent"("deviceId");
CREATE INDEX "RecognitionEvent_sessionId_idx" ON "RecognitionEvent"("sessionId");
CREATE INDEX "RecognitionEvent_occurredAt_idx" ON "RecognitionEvent"("occurredAt");
ALTER TABLE "session" ADD CONSTRAINT "session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "account" ADD CONSTRAINT "account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DeviceCredential" ADD CONSTRAINT "DeviceCredential_deviceId_fkey" FOREIGN KEY ("deviceId") REFERENCES "Device"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RecognitionSession" ADD CONSTRAINT "RecognitionSession_deviceId_fkey" FOREIGN KEY ("deviceId") REFERENCES "Device"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "RecognitionEvent" ADD CONSTRAINT "RecognitionEvent_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "RecognitionSession"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "RecognitionEvent" ADD CONSTRAINT "RecognitionEvent_deviceId_fkey" FOREIGN KEY ("deviceId") REFERENCES "Device"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
